### ISSUE TITLE
Import Users

### ISSUE THREAD

**Issue by rbvea** [rbvea/made-in-hawaii#2]

**Comment by Tigerl808** [comment]
I am trying to redesign the Producer Table, outrageous 270 columns, and force users to make complicated answers :(

**Comment by rbvea** [comment]
@Tigerl808 so, what I'm doing to import the users is running the csv through this script here: https://github.com/rbvea/made-in-hawaii/blob/master/wp-content/themes/madeinhawaii/controllers/import_users.php

Wordpress has a very specific structure, I'm adding the users to the `wp_users` table here: https://github.com/rbvea/made-in-hawaii/blob/master/wp-content/themes/madeinhawaii/controllers/import_users.php#L99

And then upserting it into the `wp_usermeta` table here: https://github.com/rbvea/made-in-hawaii/blob/master/wp-content/themes/madeinhawaii/controllers/import_users.php#L112

Well when it's not commented out anyway.

What I'm imagining is that we make a `Product` custom post type that would have different categories:
- Fresh Fruit
- Pureee
- Fresh Veggies
- Mac Nut
- Condiments
- Coffee
- Beverages
- Meat
- Seafood
- Aqua
- Health
- Floral
- Orchids
- Tropical
- Protea (whatever that is)

...etc

For users, there will be a [Relationship](https://www.advancedcustomfields.com/resources/relationship/) field on their user page where they could pick and choose which products they sell.  We'd prepopulate them by going through the csv file and mapping the columns out to the new post types.
